export const DataUnit = [
  { id: 1, name: "Kepala Sekolah" },
  { id: 2, name: "Waka. Manajamen Mutu" },
  { id: 3, name: "Waka. Kurikulum" },
  { id: 4, name: "Waka. Humastri" },
  { id: 5, name: "Waka. Sarana dan Prasarana" },
  { id: 6, name: "Waka. Kesiswaan" },
  { id: 7, name: "Kasubbag TU" },
  { id: 8, name: "Koordinator BK" },
  { id: 9, name: "Ketua Program Keahlian Teknik Otomotif" },
  { id: 10, name: "Ketua Program Keahlian TKPI" },
  { id: 11, name: "Ketua Program Keahlian APHP" },
  { id: 12, name: "Ketua Program Keahlian NKPI" },
  { id: 13, name: "Ketua Program Keahlian APi" },
  { id: 14, name: "Ketua Program Keahlian Teknik Mesin" },
  { id: 15, name: "Ketua Konsentrasi Keahlian PMHP" },
  { id: 16, name: "Ketua Konsentrasi Keahlian TKR" },
  { id: 17, name: "Koordinator BK" }, 
  { id: 18, name: "Ketua Unit Produksi" },
  { id: 19, name: "Koordinator BKK" },
];
